/// =============================================================
/// Lifex-AI — جرد دورة حياة البيانات الحساسة (Production)
/// =============================================================
library lifex_ai.core.orchestrator.lio_sensitive_lifecycle_inventory;

import 'lio_sensitive_lifecycle_contracts.dart';

/// سجل نقطة دخول لدورة حياة بيانات حساسة.
class LioSensitiveLifecycleRecord {
  const LioSensitiveLifecycleRecord({
    required this.path,
    required this.classOrFunction,
    required this.callerSurface,
    required this.operation,
    required this.dataDomain,
    required this.classification,
    required this.risk,
    required this.canonicalOwner,
    required this.passesLioEntry,
    required this.hasRealExecution,
    required this.notes,
  });

  final String path;
  final String classOrFunction;
  final String callerSurface;
  final String operation;
  final LioSensitiveDataDomain dataDomain;
  final LioLifecycleOpKind classification;
  final String risk;
  final String canonicalOwner;
  final bool passesLioEntry;
  final bool hasRealExecution;
  final String notes;
}

/// الجرد الموحّد لدورة حياة البيانات الحساسة قبل MCP الحقيقي.
class LioSensitiveLifecycleInventory {
  const LioSensitiveLifecycleInventory();

  static const inventoryId = 'LioSensitiveLifecycleInventory';

  static const legalFlow = [
    'Presentation/UI',
    'LifexAppContext',
    'LioSensitiveActionEntry',
    'ProductionLioGateway',
    'Identity',
    'Authentication',
    'Authorization',
    'Consent',
    'Purpose',
    'DataScope/Minimization',
    'SecurityPolicy',
    'Risk/ActionClassification',
    'Application operation',
    'Verification',
    'Audit',
  ];

  /// مالك منطقي معتمد لكل نطاق — ليس SQL.
  static const canonicalOwners = {
    LioSensitiveDataDomain.patientPhr: 'ProfileVault / PersonalHealthRepository',
    LioSensitiveDataDomain.clinical: 'ClinicalWatchPolicy (no export engine)',
    LioSensitiveDataDomain.healthObservation:
        'HealthObservationRepository / Persistent Store',
    LioSensitiveDataDomain.medicalDocument: 'MedicalDocument store (gap)',
    LioSensitiveDataDomain.appointment: 'UserAppointmentStore',
    LioSensitiveDataDomain.medicationRecord: 'HealthProfile medication fields',
    LioSensitiveDataDomain.emergencyRecord: 'EmergencyManager',
    LioSensitiveDataDomain.familyPrivate: 'ActiveProfileController family links',
    LioSensitiveDataDomain.walletFinancial: 'WalletManager / TransactionLedger',
    LioSensitiveDataDomain.publicEducation: 'EncyclopediaShareBridge',
    LioSensitiveDataDomain.deviceControl: 'DeviceControlCenter (policy only)',
    LioSensitiveDataDomain.medicalCatalog: 'MedicalDatabaseManager (54-ref)',
  };

  List<LioSensitiveLifecycleRecord> get productionEntries => const [
        LioSensitiveLifecycleRecord(
          path: 'lib/screens/medications_screen.dart',
          classOrFunction: '_loadCatalog',
          callerSurface: 'UI',
          operation: 'READ_MEDICAL catalog',
          dataDomain: LioSensitiveDataDomain.medicalCatalog,
          classification: LioLifecycleOpKind.readMedical,
          risk: 'low',
          canonicalOwner: 'MedicalDatabaseManager',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'via readMedicalBundle',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/screens/settings_screen.dart',
          classOrFunction: '_downloadMedicalUpdate',
          callerSurface: 'UI',
          operation: 'DOWNLOAD medical bundle',
          dataDomain: LioSensitiveDataDomain.medicalCatalog,
          classification: LioLifecycleOpKind.download,
          risk: 'medium',
          canonicalOwner: 'MedicalDatabaseManager + SearchRefreshEngine',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'via refreshMedicalKnowledge',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/screens/wallet_screen.dart',
          classOrFunction: 'wallet ops',
          callerSurface: 'UI',
          operation: 'FINANCIAL READ/WRITE',
          dataDomain: LioSensitiveDataDomain.walletFinancial,
          classification: LioLifecycleOpKind.financial,
          risk: 'high',
          canonicalOwner: 'WalletManager',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'via Entry wallet methods',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/widgets/encyclopedia_share_bar.dart',
          classOrFunction: '_share',
          callerSurface: 'UI',
          operation: 'SHARE public (≠ EXPORT PHR)',
          dataDomain: LioSensitiveDataDomain.publicEducation,
          classification: LioLifecycleOpKind.share,
          risk: 'low',
          canonicalOwner: 'EncyclopediaShareBridge',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'public brief only — not clinical export',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/screens/home_screen.dart',
          classOrFunction: 'emergency confirm',
          callerSurface: 'UI',
          operation: 'EMERGENCY_ACCESS',
          dataDomain: LioSensitiveDataDomain.emergencyRecord,
          classification: LioLifecycleOpKind.emergencyAccess,
          risk: 'high',
          canonicalOwner: 'EmergencyManager',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'EMERGENCY_LIMITED only — not full PHR',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/core/orchestrator/lio_sensitive_action_entry.dart',
          classOrFunction: 'requestClinicalPhrExport',
          callerSurface: 'Application',
          operation: 'EXPORT clinical/PHR',
          dataDomain: LioSensitiveDataDomain.patientPhr,
          classification: LioLifecycleOpKind.export,
          risk: 'critical',
          canonicalOwner: 'none — policy stub',
          passesLioEntry: true,
          hasRealExecution: false,
          notes: 'NOT_IMPLEMENTED after LIO — no fake success',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/core/orchestrator/lio_sensitive_action_entry.dart',
          classOrFunction: 'requestSensitiveDelete',
          callerSurface: 'Application',
          operation: 'DELETE sensitive record',
          dataDomain: LioSensitiveDataDomain.patientPhr,
          classification: LioLifecycleOpKind.delete,
          risk: 'high',
          canonicalOwner: 'none — policy stub (≠ ARCHIVE)',
          passesLioEntry: true,
          hasRealExecution: false,
          notes: 'NOT_IMPLEMENTED — no hard-delete engine',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/core/orchestrator/lio_sensitive_action_entry.dart',
          classOrFunction: 'requestSensitiveArchive',
          callerSurface: 'Application',
          operation: 'ARCHIVE sensitive record',
          dataDomain: LioSensitiveDataDomain.patientPhr,
          classification: LioLifecycleOpKind.archive,
          risk: 'medium',
          canonicalOwner: 'none — policy stub (≠ DELETE)',
          passesLioEntry: true,
          hasRealExecution: false,
          notes: 'NOT_IMPLEMENTED — archive store absent',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/core/orchestrator/lio_sensitive_action_entry.dart',
          classOrFunction: 'requestSensitivePrint',
          callerSurface: 'Application',
          operation: 'PRINT sensitive',
          dataDomain: LioSensitiveDataDomain.medicalDocument,
          classification: LioLifecycleOpKind.printOp,
          risk: 'medium',
          canonicalOwner: 'none — policy stub',
          passesLioEntry: true,
          hasRealExecution: false,
          notes: 'UNSUPPORTED_OPERATION — no print pipeline',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/core/orchestrator/lio_sensitive_action_entry.dart',
          classOrFunction: 'requestDeviceControl',
          callerSurface: 'Application',
          operation: 'CONTROL device',
          dataDomain: LioSensitiveDataDomain.deviceControl,
          classification: LioLifecycleOpKind.control,
          risk: 'critical',
          canonicalOwner: 'DeviceControlCenter policy only',
          passesLioEntry: true,
          hasRealExecution: false,
          notes: 'UNSUPPORTED_OPERATION — no driver execution',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/core/health_data/health_observation_application_service.dart',
          classOrFunction: 'HealthObservationApplicationService',
          callerSurface: 'Application',
          operation: 'READ_HEALTH / WRITE / UPDATE / DELETE / ARCHIVE',
          dataDomain: LioSensitiveDataDomain.healthObservation,
          classification: LioLifecycleOpKind.readHealth,
          risk: 'medium',
          canonicalOwner: 'HealthObservationRepository',
          passesLioEntry: true,
          hasRealExecution: true,
          notes:
              'Entry → Application → HealthObservationRepository → '
              'FileHealthObservationStore. DELETE ≠ ARCHIVE.',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/core/health_data/persistent_health_observation_repository.dart',
          classOrFunction: 'PersistentHealthObservationRepository',
          callerSurface: 'Repository',
          operation: 'canonical observation persistence',
          dataDomain: LioSensitiveDataDomain.healthObservation,
          classification: LioLifecycleOpKind.write,
          risk: 'medium',
          canonicalOwner: 'HealthObservationRepository',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'Production via LifexProductionComposition only',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/core/health_data/health_observation_key_reference_index.dart',
          classOrFunction: 'HealthObservationKeyReferenceIndex',
          callerSurface: 'Infrastructure',
          operation: 'key reference index + consistency',
          dataDomain: LioSensitiveDataDomain.healthObservation,
          classification: LioLifecycleOpKind.write,
          risk: 'high',
          canonicalOwner: 'HealthObservationRepository',
          passesLioEntry: true,
          hasRealExecution: true,
          notes:
              'keyId→envelope/record metadata only; INDEX_INCONSISTENT blocks '
              'REVOKE/ARCHIVE/PURGE; rebuild from store without logging secrets',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/core/health_data/health_observation_key_retention_policy.dart',
          classOrFunction: 'HealthObservationKeyRetentionPolicy',
          callerSurface: 'Infrastructure',
          operation: 'key retention / revocation / archival',
          dataDomain: LioSensitiveDataDomain.healthObservation,
          classification: LioLifecycleOpKind.archive,
          risk: 'high',
          canonicalOwner: 'HealthObservationRepository',
          passesLioEntry: true,
          hasRealExecution: true,
          notes:
              'CURRENT/ACTIVE_FOR_DECRYPTION/RETIRED/REVOKED/ARCHIVED; '
              'no auto-delete; RETENTION_REQUIRED when still referenced',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/core/health_data/health_observation_key_lifecycle.dart',
          classOrFunction: 'HealthObservationKeyLifecycle',
          callerSurface: 'Infrastructure',
          operation: 'key rotation + recovery + retention',
          dataDomain: LioSensitiveDataDomain.healthObservation,
          classification: LioLifecycleOpKind.write,
          risk: 'high',
          canonicalOwner: 'HealthObservationRepository',
          passesLioEntry: true,
          hasRealExecution: true,
          notes:
              'DEK versions in SecureSecretStore; rotate decrypt→validate→'
              're-encrypt→verify then promote; retention policy gated',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/core/health_data/encrypted_health_observation_store.dart',
          classOrFunction: 'EncryptedHealthObservationStore',
          callerSurface: 'Infrastructure',
          operation: 'AES-256-GCM at-rest encryption',
          dataDomain: LioSensitiveDataDomain.healthObservation,
          classification: LioLifecycleOpKind.write,
          risk: 'medium',
          canonicalOwner: 'HealthObservationRepository',
          passesLioEntry: true,
          hasRealExecution: true,
          notes:
              'LIFEXHOB2 + keyId; DEK via HealthObservationKeyLifecycle; '
              'no plaintext HealthObservation on disk',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/core/health_data/file_health_observation_store.dart',
          classOrFunction: 'FileHealthObservationStore',
          callerSurface: 'Infrastructure',
          operation: 'ciphertext file bytes',
          dataDomain: LioSensitiveDataDomain.healthObservation,
          classification: LioLifecycleOpKind.write,
          risk: 'medium',
          canonicalOwner: 'HealthObservationRepository',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'inner store for EncryptedHealthObservationStore only',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/screens/appointments_screen.dart',
          classOrFunction: '_remove',
          callerSurface: 'UI',
          operation: 'DELETE local appointment',
          dataDomain: LioSensitiveDataDomain.appointment,
          classification: LioLifecycleOpKind.delete,
          risk: 'medium',
          canonicalOwner: 'UserAppointmentStore',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'via authorizeThenRun then store.removeOrCancel',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/screens/medication_alarm_screen.dart',
          classOrFunction: 'alarm delete',
          callerSurface: 'UI',
          operation: 'DELETE medication alarm',
          dataDomain: LioSensitiveDataDomain.medicationRecord,
          classification: LioLifecycleOpKind.delete,
          risk: 'medium',
          canonicalOwner: 'MedicationAlarmLedger',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'DELETE ≠ ARCHIVE; gated via Entry',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/screens/emergency_contacts_screen.dart',
          classOrFunction: 'contact delete',
          callerSurface: 'UI',
          operation: 'DELETE emergency contact',
          dataDomain: LioSensitiveDataDomain.emergencyRecord,
          classification: LioLifecycleOpKind.delete,
          risk: 'medium',
          canonicalOwner: 'EmergencyPhoneContactsRegistry / profile',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'DELETE local trusted contact via Entry',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/screens/personal_shelf_screen.dart',
          classOrFunction: '_drop',
          callerSurface: 'UI',
          operation: 'DELETE personal shelf item',
          dataDomain: LioSensitiveDataDomain.publicEducation,
          classification: LioLifecycleOpKind.delete,
          risk: 'low',
          canonicalOwner: 'PersonalShelfStore',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'user-owned download DELETE via Entry',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/screens/thumbnail_manage_screen.dart',
          classOrFunction: 'camera note delete',
          callerSurface: 'UI',
          operation: 'DELETE thumbnail/camera note',
          dataDomain: LioSensitiveDataDomain.medicalDocument,
          classification: LioLifecycleOpKind.delete,
          risk: 'medium',
          canonicalOwner: 'ProfileBoxStore',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'DELETE local note thumbnail via Entry',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/screens/booking_workspace_screen.dart',
          classOrFunction: 'booking delete',
          callerSurface: 'UI',
          operation: 'DELETE local booking',
          dataDomain: LioSensitiveDataDomain.appointment,
          classification: LioLifecycleOpKind.delete,
          risk: 'medium',
          canonicalOwner: 'UnifiedBookingService',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'DELETE ≠ ARCHIVE; gated via Entry',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/screens/unit_branch_records_screen.dart',
          classOrFunction: 'branch record delete',
          callerSurface: 'UI',
          operation: 'DELETE unit branch record',
          dataDomain: LioSensitiveDataDomain.patientPhr,
          classification: LioLifecycleOpKind.delete,
          risk: 'medium',
          canonicalOwner: 'ProfileBoxStore',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'local branch DELETE via Entry — not PHR hard-delete engine',
        ),
        LioSensitiveLifecycleRecord(
          path: 'lib/features/scheduling/user_appointment_store.dart',
          classOrFunction: 'UserAppointmentStore',
          callerSurface: 'Application',
          operation: 'WRITE/DELETE appointments',
          dataDomain: LioSensitiveDataDomain.appointment,
          classification: LioLifecycleOpKind.write,
          risk: 'low',
          canonicalOwner: 'UserAppointmentStore',
          passesLioEntry: true,
          hasRealExecution: true,
          notes: 'mutations must authorize via Entry before store write',
        ),
      ];

  static const uiForbiddenProviderTypes = [
    'MedicalDatabaseManager',
    'WalletManager',
    'TransactionService',
    'PaymentController',
    'SubscriptionBillingManager',
    'EmergencyManager',
    'HealthRepository',
    'DeviceControlCenter',
  ];
}
