/// =============================================================
/// Lifex-AI — مختبر أجهزة
/// الملف: lab_kind.dart
/// فئات محاكاة. ليست كتالوج السوق.
/// =============================================================
library lifex_ai.core.device_lab.lab_kind;

enum LabKind {
  generic,
  phone,
  tablet,
  laptop,
  desktop,
  tv,
  monitor,
  projector,
  gameConsole,
  mediaPlayer,
  eReader,
  watch,
  earbuds,
  headset,
  fitnessBand,
  smartGlasses,
  homeHub,
  light,
  homeSwitch,
  lock,
  door,
  window,
  thermostat,
  ac,
  fan,
  fridge,
  washingMachine,
  oven,
  vacuum,
  robot,
  homeCamera,
  homeAlarm,
  vehicle,
  car,
  bus,
  truck,
  motorcycle,
  ev,
  infotainment,
  vehicleSensor,
  vehicleGateway,
  patientMonitor,
  ecg,
  spo2,
  bloodPressure,
  temperatureProbe,
  glucose,
  infusionPump,
  ventilator,
  defibrillator,
  ultrasound,
  medicalCamera,
  medicalDisplay,
  medicalGateway,
  analyzer,
  labMachine,
  sampleReader,
  barcodeScanner,
  labDisplay,
  labGateway,
  plc,
  robotArm,
  motor,
  industrialPump,
  valve,
  industrialSensor,
  industrialController,
  industrialGateway,
  weatherStation,
  airQuality,
  temperatureSensor,
  humiditySensor,
  pressureSensor,
  environmentGateway,
  brailleDisplay,
  hearingDevice,
  assistiveSwitch,
  accessibilityRemote,
  voiceDevice,
  wheelchair,
  smartWheelchair,
  securityCamera,
  motionSensor,
  doorSensor,
  securityAlarm,
  securityHub,
  router,
  accessPoint,
  networkSwitch,
  gateway,
  server,
  networkService,
}

extension LabKindX on LabKind {
  String get category => name;
  bool get medicalSimulation => const {
        LabKind.patientMonitor,
        LabKind.ecg,
        LabKind.spo2,
        LabKind.bloodPressure,
        LabKind.temperatureProbe,
        LabKind.glucose,
        LabKind.infusionPump,
        LabKind.ventilator,
        LabKind.defibrillator,
        LabKind.ultrasound,
        LabKind.medicalCamera,
        LabKind.medicalDisplay,
        LabKind.medicalGateway,
      }.contains(this);

  bool get industrialSimulation => name.startsWith('plc') ||
      this == LabKind.robotArm ||
      this == LabKind.motor ||
      this == LabKind.industrialPump ||
      this == LabKind.valve ||
      this == LabKind.industrialSensor ||
      this == LabKind.industrialController ||
      this == LabKind.industrialGateway;
}
